apiVersion: batch.upv.es/v1
kind: BatchJob
metadata:
  name: job1
spec:
  queueName: high-priority-queue
  priority: 10
  jobDetails:
    image: ubuntu:20.04
    commands:
      - "echo 'Job1: Hello, World!'"
      - "sleep 15"
      - "echo 'Job1: Job Completed'"