apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: batchjobs.batch.upv.es
spec:
  group: batch.upv.es
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                queueName:
                  type: string
                priority:
                  type: integer
                jobDetails:
                  type: object
                  properties:
                    image:
                      type: string
                    commands:
                      type: array
                      items:
                        type: string
  scope: Namespaced
  names:
    plural: batchjobs
    singular: batchjob
    kind: BatchJob
    shortNames:
    - bj
