apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: queues.batch.upv.es
spec:
  group: batch.upv.es
  names:
    plural: queues
    singular: queue
    kind: Queue
    shortNames:
      - que
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                priority:
                  type: integer
                slots:
                  type: integer
            status:
              type: object
              properties:
                runningJobs:
                  type: array
                  items: 
                    type: string
                queuedJobs:
                  type: array
                  items: 
                    type: string
