apiVersion: batch.upv.es/v1
kind: BatchJob
metadata:
  name: example-batchjob
spec:
  queueName: high-priority-queue
  priority: 100
  slots: 2
  jobDetails:
    image: "python:3.8-slim"
    commands: 
      - "python"
      - "-c"
      - "print('Hola Mundo desde un BatchJob')"
